2022-09-21 01:21:51,912 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 1751483ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 01:37:52,741 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 920333ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 02:28:01,726 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 2768576ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 02:36:16,899 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 320417ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 03:07:05,688 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 1730939ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 03:24:36,632 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 1010931ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 04:47:04,265 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 4906589ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 06:47:56,252 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 7211883ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 08:00:02,644 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 4285604ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 09:39:45,587 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 5942597ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 11:27:53,625 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 2887474ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 12:01:22,561 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 1968212ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 13:11:40,667 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 176802ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 13:31:38,993 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 1157819ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 13:49:28,750 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 1029690ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 14:05:28,155 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 919356ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 14:21:19,563 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 910592ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 14:38:21,589 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 981621ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 15:05:09,571 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 1487599ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 15:19:18,897 ERROR 9094 nodejs.ClusterClientNoResponseError: client no response in 808936ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 9094
hostname: hahas-MBP.lan

2022-09-21 17:53:22,413 ERROR 15066 nodejs.ClusterClientNoResponseError: client no response in 146430ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 15066
hostname: hahas-MBP.lan

2022-09-21 18:05:20,909 ERROR 15066 nodejs.ClusterClientNoResponseError: client no response in 677911ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 15066
hostname: hahas-MBP.lan

2022-09-22 16:53:46,659 ERROR 38633 nodejs.ClusterClientNoResponseError: client no response in 1398487ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 38633
hostname: hahas-MBP.lan

2022-09-25 09:37:46,336 ERROR 15927 [-/127.0.0.1/-/153ms GET /default/getListById/undefined] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
    at Query.Sequence._packetToError (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:65:19)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:54:5
    sql: SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id WHERE type_id=undefined
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'undefined' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id WHERE type_id=undefined"
name: "ER_BAD_FIELD_ERRORError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 09:38:56,116 ERROR 15927 [-/127.0.0.1/-/158ms GET /default/getListById/undefined] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
    at Query.Sequence._packetToError (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:65:19)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:54:5
    sql: SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id WHERE type_id=undefined
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'undefined' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id WHERE type_id=undefined"
name: "ER_BAD_FIELD_ERRORError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 09:39:19,976 ERROR 15927 [-/127.0.0.1/-/145ms GET /default/getListById/undefined] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
    at Query.Sequence._packetToError (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:65:19)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:54:5
    sql: SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id WHERE type_id=undefined
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'undefined' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id WHERE type_id=undefined"
name: "ER_BAD_FIELD_ERRORError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 09:40:56,641 ERROR 15927 [-/127.0.0.1/-/150ms GET /default/getListById/undefined] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
    at Query.Sequence._packetToError (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:65:19)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:54:5
    sql: SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id WHERE type_id=undefined
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'undefined' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id WHERE type_id=undefined"
name: "ER_BAD_FIELD_ERRORError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 10:57:04,907 ERROR 15927 [-/127.0.0.1/-/10066ms GET /default/getTypeInfo] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT * FROM `type`
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 10:57:14,923 ERROR 15927 [-/undefined/-/10002ms GET /default/getTypeInfo] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT * FROM `type`
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
headerSent: true
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 10:57:22,309 ERROR 15927 [-/127.0.0.1/-/10003ms GET /default/getTypeInfo] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT * FROM `type`
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 10:57:32,318 ERROR 15927 [-/127.0.0.1/-/10002ms GET /default/getTypeInfo] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT * FROM `type`
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 10:57:42,846 ERROR 15927 [-/127.0.0.1/-/10004ms GET /default/getTypeInfo] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT * FROM `type`
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 10:57:43,137 ERROR 15927 [-/127.0.0.1/-/10025ms GET /default/getArticleList] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 10:57:52,851 ERROR 15927 [-/127.0.0.1/-/10002ms GET /default/getTypeInfo] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT * FROM `type`
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 11:10:38,896 ERROR 15927 [-/127.0.0.1/-/10005ms GET /default/getArticleList] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 11:12:53,230 ERROR 15927 [-/127.0.0.1/-/10005ms GET /default/getArticleList] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 11:12:54,213 ERROR 15927 [-/127.0.0.1/-/10014ms GET /default/getTypeInfo] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT * FROM `type`
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 11:13:12,444 ERROR 15927 [-/127.0.0.1/-/10002ms GET /default/getArticleList] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 11:13:15,051 ERROR 15927 [-/127.0.0.1/-/10003ms GET /default/getArticleList] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 11:13:20,176 ERROR 15927 [-/127.0.0.1/-/10004ms GET /default/getArticleList] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: SELECT article.id as id ,article.title as title ,article.intro as intro ,FROM_UNIXTIME(article.addTime,'%Y-%m-%d %H:%i:%s') as addTime ,article.view_count as view_count ,type.typeName as typeName FROM article LEFT JOIN type ON article.type_id = type.id
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
name: "ETIMEDOUTError"
pid: 15927
hostname: hahas-MBP.lan

2022-09-25 11:14:16,448 ERROR 20822 [-/127.0.0.1/-/1ms GET /] nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    --------------------
    at Protocol._enqueue (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errorno: "ETIMEDOUT"
code: "ETIMEDOUT"
syscall: "connect"
fatal: true
name: "ETIMEDOUTError"
pid: 20822
hostname: hahas-MBP.lan

